[REVIEW][FEATURE][GAWE-49] - Implement reset password business logic
Blue-Habit/gawean-android-app pull request #19
Opened 2023-08-16 17:12 UTC by fauzanramadhani

#### Description

Implement reset password business logic.

#### Ticket Reference(s)

[GAWE-49](https://bluehabit.atlassian.net/browse/GAWE-49)

#### Validation

##### UI Changes

> Screenshot or video of UI-related changes

##### Coverage

> Test coverage screenshot.

N/A

#### Note(s)

@triandamai @WhyUReRenldI @azkifairuz

2023-08-17 08:23 UTC, triandamai commented on data/data-authentication/src/main/java/com/bluehabit/eureka/data/authentication/datasource/remote/response/RequestResetPasswordResponse.kt
> +data class RequestResetPasswordResponse(
langsung aja `data:Any` statusCode,message,sama data sudah di cover di BaseResponse

2023-08-17 08:23 UTC, triandamai commented on data/data-authentication/src/main/java/com/bluehabit/eureka/data/authentication/datasource/remote/response/ResetPasswordResponse.kt
> +data class ResetPasswordResponse(
langsung aja `data:Any` statusCode,message,sama data sudah di cover di BaseResponse

2023-08-21 14:39 UTC, fauzanramadhani commented on data/data-authentication/src/main/java/com/bluehabit/eureka/data/authentication/datasource/remote/response/LinkConfirmationResponse.kt
> +data class Data(
done!

2023-08-21 14:39 UTC, fauzanramadhani commented on data/data-authentication/src/main/java/com/bluehabit/eureka/data/authentication/datasource/remote/response/RequestResetPasswordResponse.kt
> +data class RequestResetPasswordResponse(
done!

2023-08-21 14:39 UTC, fauzanramadhani commented on data/data-authentication/src/main/java/com/bluehabit/eureka/data/authentication/datasource/remote/response/ResetPasswordResponse.kt
> +data class ResetPasswordResponse(
done!

2023-08-21 16:15 UTC, triandamai requested changes
cek dolo

2023-08-21 16:15 UTC, triandamai commented on data/data-authentication/src/main/java/com/bluehabit/eureka/data/authentication/repositories/ResetPasswordRepository.kt
> +    ): Response<BaseResponse<LinkConfirmationResponse>> =
ga perlu `BaseResponse` langsung aja `Response<LinkCOnfirmationResponse>`

2023-08-21 16:15 UTC, triandamai commented on data/data-authentication/src/main/java/com/bluehabit/eureka/data/authentication/repositories/ResetPasswordRepository.kt
> +    ): Response<BaseResponse<LinkConfirmationResponse>> =
karena dari `safeApiCall` suda menghandle

2023-08-21 16:15 UTC, triandamai commented on data/data-authentication/src/main/java/com/bluehabit/eureka/data/authentication/repositories/ResetPasswordRepository.kt
> +    ): Response<BaseResponse<Any>> = safeApiCall {
ga perlu `BaseResponse `langsung aja `Response<LinkCOnfirmationResponse>`

2023-08-22 14:10 UTC, fauzanramadhani commented on data/data-authentication/src/main/java/com/bluehabit/eureka/data/authentication/repositories/ResetPasswordRepository.kt
> +    ): Response<BaseResponse<LinkConfirmationResponse>> =
done mas

2023-08-22 14:11 UTC, fauzanramadhani commented on data/data-authentication/src/main/java/com/bluehabit/eureka/data/authentication/repositories/ResetPasswordRepository.kt
> +    ): Response<BaseResponse<Any>> = safeApiCall {
done mas

2023-08-22 14:31 UTC, merged