[REVIEW][FEATURE][GAWE-95] - Create item task component
Blue-Habit/gawean-android-app pull request #25
Opened 2023-08-25 15:10 UTC by fauzanramadhani

#### Description

Create item task component

#### Ticket Reference(s)

[GAWE-95](https://bluehabit.atlassian.net/browse/95)

#### Validation

##### UI Changes

> Screenshot or video of UI-related changes
![image](https://github.com/Blue-Habit/gawean-android-app/assets/95521299/8e398290-ec77-4961-a04e-db63d4c34ee3)

##### Coverage

> Test coverage screenshot.

N/A

#### Note(s)

> Mention other user or extra note unrelated to the MR here.

2023-08-27 05:09 UTC, triandamai approved these changes

2023-08-27 05:10 UTC, triandamai requested changes

2023-08-27 05:10 UTC, triandamai commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/item/itemTask/ItemTask.kt
> +        checked = checked,
ketika checked warna background nya ganti
cek figmanya lagi ya

2023-08-28 08:51 UTC, fauzanramadhani commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/item/itemTask/ItemTask.kt
> +        checked = checked,
done mas

2023-08-28 08:54 UTC, triandamai approved these changes

2023-08-28 09:02 UTC, merged