[REVIEW][FEATURE][GAWE-57] - Create Dialog Component
Blue-Habit/gawean-android-app pull request #3
Opened 2023-08-09 11:40 UTC by azkifairuz

#### Description

> Create Dialog Component

#### Ticket Reference(s)

[GAWE-57](https://bluehabit.atlassian.net/browse/GAWE-57)

#### Validation

##### UI Changes

> Screenshot or video of UI-related changes

##### Coverage

> Test coverage screenshot.

N/A

#### Note(s)

> @triandamai @WhyUReRenldI

2023-08-09 12:16 UTC, triandamai commented
mana evidence nya

2023-08-09 12:27 UTC, triandamai commented
Sepertinya belum mendekati desain @azkifairuz ?

2023-08-09 12:36 UTC, triandamai requested changes
check dulu

2023-08-09 12:36 UTC, triandamai commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/dialog-component.kt
> +fun DialogComponent(isSuccess: Boolean = true, label: String, message: String, btnText: String) {
Penamaanya diganti aja jadi `DialogConfirmation`

2023-08-09 12:36 UTC, triandamai commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/dialog-component.kt
> +    Card(
Langsung aja di wrapping sama Dialog
```kotlin
Dialog(){
 // content disini
}
```

2023-08-09 12:36 UTC, triandamai commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/dialog-component.kt
> +    Card(
Kalau mau dibikin reusable mending gini aja

```kotlin
@Composable
fun DialogConfirmation(
 show:Boolean=false,
 icon:(@Composable ()->Unit)?=null,
 action:@Composable ()->Unit={},
 title:String=String.Empty,
 message:String=String.Empty,
 onConfirm:()->Unit={}
){
 if(show){
  Dialog(){
    //content disini
  }
 }
}

```

2023-08-09 12:36 UTC, triandamai commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/dialog-component.kt
> +                        fontFamily = FontFamily(Font(R.font.inter_semi_bold)),
pake `MaterialTheme.typhography.h1` misal

2023-08-09 13:32 UTC, WhyUReRenldI commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/dialog-component.kt
> +    Card(
![image](https://github.com/Blue-Habit/gawean-android-app/assets/118540362/67d502a5-7f58-4940-ba20-9536f1cf629d)

Sepertinya font typenya kurang detail, boleh di cek dari mockupnya ya

2023-08-09 13:34 UTC, WhyUReRenldI commented
![image](https://github.com/Blue-Habit/gawean-android-app/assets/118540362/958b7fc5-7342-4a56-a1a9-7ac5fe15a70c)

Sepertinya ukuran typenya kurang detail dari design mockup, boleh di cek lagi ya @azkifairuz

2023-08-09 15:07 UTC, triandamai requested changes
check dolo

2023-08-09 15:07 UTC, triandamai commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/DialogConfirmation.kt
> +                            fontWeight = FontWeight(600),
FontWeight.W600

2023-08-09 15:07 UTC, triandamai commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/DialogConfirmation.kt
> +                            fontWeight = FontWeight(400),
FontWeight.W400

2023-08-09 15:07 UTC, triandamai commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/DialogConfirmation.kt
> +                    verticalArrangement = Arrangement.spacedBy(35.dp), horizontalAlignment = Alignment.CenterHorizontally
horizontalAlignment nya di Enter aja lagi

2023-08-09 15:07 UTC, triandamai commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/DialogConfirmation.kt
> +                    .background(color = Color(0xFFFFFFFF), shape = RoundedCornerShape(8.dp))
shape nya di Enter gaes

2023-08-09 15:07 UTC, triandamai commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/DialogConfirmation.kt
> +                            .width(103.dp)
apakah yakin semua layar pakai 103 dp jadi?

2023-08-10 03:02 UTC, azkifairuz commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/dialog-component.kt
> +    Card(
done bang

2023-08-10 03:02 UTC, azkifairuz commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/dialog-component.kt
> +                        fontFamily = FontFamily(Font(R.font.inter_semi_bold)),
done

2023-08-10 03:04 UTC, azkifairuz commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/DialogConfirmation.kt
> +                            .width(103.dp)
g yakin sih bang, berati mending jangan dikasih width? atau ada cara biar responsivenya?

2023-08-10 03:44 UTC, azkifairuz commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/DialogConfirmation.kt
> +                            fontWeight = FontWeight(400),
done

2023-08-10 03:44 UTC, azkifairuz commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/DialogConfirmation.kt
> +                    verticalArrangement = Arrangement.spacedBy(35.dp), horizontalAlignment = Alignment.CenterHorizontally
done

2023-08-10 03:44 UTC, azkifairuz commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/DialogConfirmation.kt
> +                    .background(color = Color(0xFFFFFFFF), shape = RoundedCornerShape(8.dp))
done

2023-08-10 03:48 UTC, azkifairuz commented
> ![image](https://user-images.githubusercontent.com/118540362/259425804-958b7fc5-7342-4a56-a1a9-7ac5fe15a70c.png)
> 
> Sepertinya ukuran typenya kurang detail dari design mockup, boleh di cek lagi ya @azkifairuz

done bang

2023-08-10 06:15 UTC, triandamai approved these changes
LGTM!

2023-08-11 00:19 UTC, merged