[WIP][FEATURE][GAWE-114]- create datepicker component
Blue-Habit/gawean-android-app pull request #32
Opened 2023-08-30 09:04 UTC by azkifairuz

#### Description

> Description of features, bugs, improvements or any changes in this MR.

#### Ticket Reference(s)

[GAWE-114](https://bluehabit.atlassian.net/browse/GAWE-114)

#### Validation

##### UI Changes

> ![gambar](https://github.com/Blue-Habit/gawean-android-app/assets/63065606/933891b0-d8a2-4618-95da-7c08cf804552)

##### Coverage

> Test coverage screenshot.

N/A

#### Note(s)

> @triandamai @WhyUReRenldI @fauzanramadhani 
 masih gbisa cara menggunakan datepickernya, pas di pake selalu dpt render issue, minta tolong arahan nya ges

2023-08-30 12:31 UTC, triandamai commented
udah coba run previewnya ? @azkifairuz

2023-08-30 12:33 UTC, triandamai requested changes

2023-08-30 12:33 UTC, triandamai commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/sheet/DatePickerBottomSheet.kt
> +fun DatePickerBottomSheet(){
butuh parameter `selectedDate` sama `onChange(date)`

2023-08-30 12:33 UTC, triandamai commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/sheet/DatePickerBottomSheet.kt
> +    val selectedDate = remember { mutableStateOf(LocalDate.now()) }
karena uda pake `onChange` jadi gaperlu di bikin state disini

2023-08-30 12:33 UTC, triandamai commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/sheet/DatePickerBottomSheet.kt
> +                selectedDate.value = snappedDate
panggil `onChange`

2023-08-30 16:56 UTC, azkifairuz commented
> udah coba run previewnya ? @azkifairuz

udah , tapi malah polos putih gitu

2023-08-30 16:59 UTC, azkifairuz commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/sheet/DatePickerBottomSheet.kt
> +fun DatePickerBottomSheet(){
selected date tipenya apa bang?

2023-09-03 08:37 UTC, fauzanramadhani commented
ini preview setelah gua terapin beberapa perubahan di atas, mngkin masih kurang bagus dan bisa di sesuaikan lagi ki.
![image](https://github.com/Blue-Habit/gawean-android-app/assets/95521299/5fabe867-9bf0-423c-838c-d25a9608a82e)
![image](https://github.com/Blue-Habit/gawean-android-app/assets/95521299/5731790a-9e98-408c-a8ab-eba245c13d88)

2023-09-03 13:37 UTC, triandamai requested changes

2023-09-03 13:37 UTC, triandamai commented on core/core-component/src/main/java/com/bluehabit/core/ui/components/sheet/DatePickerBottomSheet.kt
> +    onChange: (date: LocalDate) -> Unit ={}
kurang parameter `selectedDate`

2023-09-05 02:14 UTC, triandamai approved these changes

2023-09-05 02:14 UTC, merged