[WIP][FEATURE][GAWE-74] - create edit profile page
Blue-Habit/gawean-android-app pull request #35
Opened 2023-08-31 09:36 UTC by azkifairuz

#### Description

> edit profile page

#### Ticket Reference(s)

[GAWE-74](https://bluehabit.atlassian.net/browse/GAWE-74)

#### Validation

##### UI Changes

>
![gambar](https://github.com/Blue-Habit/gawean-android-app/assets/63065606/ccc5ab36-7821-44ce-9afc-00bd81ce8b63)
![gambar](https://github.com/Blue-Habit/gawean-android-app/assets/63065606/1805df92-06d7-446d-bcba-d025416620d0)

##### Coverage

> Test coverage screenshot.

N/A

#### Note(s)

> Mention other user or extra note unrelated to the MR here.

2023-08-31 10:19 UTC, triandamai requested changes

2023-08-31 10:19 UTC, triandamai commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/editProfile/EditProfileScreen.kt
> +    state: EditProfileState = EditProfileState(),
Ini ga perlu ya..di contract udah di provide, actionnya juga

2023-08-31 10:19 UTC, triandamai commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/editProfile/EditProfileScreen.kt
> +    onNewNameChange: (String) -> Unit = {},
Ini gaperlu

2023-08-31 10:19 UTC, triandamai commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/editProfile/EditProfileScreen.kt
> +                R.drawable.dummy_avatar_1
Ga perlu di kasih ini lgsg aja` .orEmpty()` dan ketika error dia bakal manggil di builder error

2023-08-31 10:19 UTC, triandamai commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/editProfile/EditProfileScreen.kt
> +    val scope = rememberCoroutineScope()
Ga perlu bikin coroutine scope ya...udah di provide sama contarct langsung aja makenya `launch{}`

2023-08-31 10:19 UTC, triandamai commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/editProfile/EditProfileScreen.kt
> +                        IconButton(onClick = {  }) {
Kayaknya ga dikadih button jg bisa deh

2023-08-31 10:46 UTC, azkifairuz commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/editProfile/EditProfileScreen.kt
> +    onNewNameChange: (String) -> Unit = {},
buat onChangenya

2023-08-31 10:49 UTC, azkifairuz commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/editProfile/EditProfileScreen.kt
> +                        IconButton(onClick = {  }) {
pas g dikasih button g ngefek
![gambar](https://github.com/Blue-Habit/gawean-android-app/assets/63065606/d520805d-85da-4781-9993-26715de4e4bc)

2023-09-03 13:38 UTC, triandamai approved these changes

2023-09-03 13:38 UTC, merged