Feature/gawe 63
Blue-Habit/gawean-android-app pull request #7
Opened 2023-08-10 19:32 UTC by azkifairuz

#### Description

>Screen Instruction Reset.

#### Ticket Reference(s)

[GAWE-64](https://bluehabit.atlassian.net/browse/GAWE-63)

#### Validation

##### UI Changes

>

##### Coverage

>  ![gambar](https://github.com/Blue-Habit/gawean-android-app/assets/63065606/9df3c5c3-9515-401a-a38f-54419d97a166)

N/A

#### Note(s)

> Note
masih bingung gima buat nge direct ke email

2023-08-10 23:34 UTC, triandamai commented
Judul PR nya benerin dulu ya

2023-08-11 04:00 UTC, triandamai commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/resetPassword/screen/InstructionResetScreen.kt
> +    tryAgain: () -> Unit = {},
ganti jadi `onRetry` aja

2023-08-11 04:00 UTC, triandamai commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/resetPassword/screen/InstructionResetScreen.kt
> +    openEmail: () -> Unit = {},
ganti jadi `onOpenEmailApp` aja

2023-08-11 04:00 UTC, triandamai commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/resetPassword/screen/InstructionResetScreen.kt
> +        verticalArrangement = Arrangement.spacedBy(95.dp.from(context = context)), horizontalAlignment = Alignment.CenterHorizontally
horizontal alignment nya enter aja

2023-08-11 04:01 UTC, triandamai commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/resetPassword/screen/InstructionResetScreen.kt
> +                    text = "Cek email anda dan klik link pada instruksi tersebut.",
extract ke string resource aja

2023-08-11 04:01 UTC, triandamai commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/resetPassword/screen/InstructionResetScreen.kt
> +                    text = "Instruksi Terkirim!",
extract ke string resource aja

2023-08-11 04:01 UTC, triandamai commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/resetPassword/screen/InstructionResetScreen.kt
> +                    text = "Buka Email",
extract ke string resource aja

2023-08-11 04:01 UTC, triandamai commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/resetPassword/screen/InstructionResetScreen.kt
> +                    text = "Tidak menerima email? Coba cek spam",
extract ke string resource aja

2023-08-11 04:01 UTC, triandamai commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/resetPassword/screen/InstructionResetScreen.kt
> +                    text = "atau",
extract ke string resource aja

2023-08-11 04:01 UTC, triandamai commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/resetPassword/screen/InstructionResetScreen.kt
> +                    text = "coba lagi dengan alamat email yang lain.",
extract ke string resource aja

2023-08-11 04:02 UTC, triandamai commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/resetPassword/screen/InstructionResetScreen.kt
> +fun DefaultPreview() {
Hindari pake Default Preview namingnya pasti bentrok sama yang lain nanti
misal 

```kotlin
fun PreviewInstructionScreen()
```

2023-08-11 04:03 UTC, triandamai commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/resetPassword/screen/InstructionResetScreen.kt
> +                        contentDescription = "logo"
formatiing ulang masih blm rapih

2023-08-11 04:04 UTC, triandamai commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/resetPassword/screen/InstructionResetScreen.kt
> +                contentDescription = "logo"
contetn descriptionnya di perjelas lagi supaya ada maknanya

2023-08-11 04:04 UTC, triandamai requested changes
revisi

2023-08-11 04:27 UTC, azkifairuz commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/resetPassword/screen/InstructionResetScreen.kt
> +    openEmail: () -> Unit = {},
done

2023-08-11 04:27 UTC, azkifairuz commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/resetPassword/screen/InstructionResetScreen.kt
> +        verticalArrangement = Arrangement.spacedBy(95.dp.from(context = context)), horizontalAlignment = Alignment.CenterHorizontally
done

2023-08-11 04:27 UTC, azkifairuz commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/resetPassword/screen/InstructionResetScreen.kt
> +                    text = "Cek email anda dan klik link pada instruksi tersebut.",
done

2023-08-11 04:27 UTC, azkifairuz commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/resetPassword/screen/InstructionResetScreen.kt
> +                    text = "Instruksi Terkirim!",
done

2023-08-11 04:35 UTC, triandamai requested changes
Cek cek

2023-08-11 04:35 UTC, triandamai commented on feature/feature-authentication/src/main/java/com/bluehabit/eureka/feature/authentication/resetPassword/screen/InstructionResetScreen.kt
> +                    text = "Buka Email",
Masih blm di extract nih

2023-08-11 09:05 UTC, triandamai approved these changes

2023-08-11 12:57 UTC, merged