[REVIEW][FEATURE][GAWE-50]
Blue-Habit/gawean-android-app pull request #8
Opened 2023-08-11 06:37 UTC by azkifairuz

#### Description

> Description of features, bugs, improvements or any changes in this MR.

#### Ticket Reference(s)

[GAWE-50](https://bluehabit.atlassian.net/browse/GAWE-50)

#### Validation

##### UI Changes

> Screenshot or video of UI-related changes

##### Coverage

> Test coverage screenshot.

N/A

#### Note(s)

> masih blm ngerti dan meraba raba

2023-08-11 09:03 UTC, triandamai commented on data/data-authentication/src/main/java/com/bluehabit/eureka/data/authentication/repositories/SetNewPasswordRepository.kt
> +                setBody(
set header nya disini

2023-08-11 09:04 UTC, triandamai requested changes
cek

2023-08-11 12:56 UTC, triandamai commented on data/data-authentication/src/main/java/com/bluehabit/eureka/data/authentication/repositories/SetNewPasswordRepository.kt
> +                setBody(
```kotlin

client.post("") {
    headers {
        append(HttpHeaders.Accept, "text/html")
        append(HttpHeaders.Authorization, "abc123")
        append(HttpHeaders.UserAgent, "ktor client")
    }
    setBody(
      //ini body
    )
}
```

2023-08-12 13:22 UTC, triandamai requested changes

2023-08-12 13:22 UTC, triandamai commented on data/data-authentication/src/main/java/com/bluehabit/eureka/data/authentication/AuthConstant.kt
> +    const val SESSION_TOKEN_RESET_PW = "sessionToken"
jangan disingkat langsun PASSWORD aja

2023-08-12 13:22 UTC, triandamai commented on data/data-authentication/src/main/java/com/bluehabit/eureka/data/authentication/repositories/SetNewPasswordRepository.kt
> +                    append(HttpHeaders.Authorization, "abc123")
ga perlu Authorization,Accept,UserAgent

2023-08-14 07:40 UTC, triandamai requested changes
cek dulu

2023-08-14 07:40 UTC, triandamai commented on data/data-authentication/src/main/java/com/bluehabit/eureka/data/authentication/repositories/SetNewPasswordRepository.kt
> +                    append("4adf-3ed", pref.getPersistData(AuthConstant.SESSION_TOKEN_RESET_PASSWORD).orEmpty())
ini taro di constanta aja @azkifairuz

2023-08-14 08:31 UTC, azkifairuz commented on data/data-authentication/src/main/java/com/bluehabit/eureka/data/authentication/repositories/SetNewPasswordRepository.kt
> +                    append("4adf-3ed", pref.getPersistData(AuthConstant.SESSION_TOKEN_RESET_PASSWORD).orEmpty())
yg token "4asnkancjk" nya
?

2023-08-14 08:39 UTC, triandamai commented on data/data-authentication/src/main/java/com/bluehabit/eureka/data/authentication/repositories/SetNewPasswordRepository.kt
> +                    append("4adf-3ed", pref.getPersistData(AuthConstant.SESSION_TOKEN_RESET_PASSWORD).orEmpty())
yang '4adf-3ed' @azkifairuz 
taro di `AuthConstant` aja misal `const val keyHeaderSessionId = "4adf-3ed"`

2023-08-14 09:26 UTC, triandamai approved these changes

2023-08-15 12:40 UTC, merged